[project]
name = "route-finder"
version = "0.1.0"
description = "Finds a route between structures in a minecraft world using the Christofides algorithm"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "networkx>=3.6.1",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
]
